### PR TITLE
[ON HOLD] Several improvements

### PR DESCRIPTION
**Pull request by MangelMaxime**
**Do not merge yet**

I know it's seems a lot but all the changes are only suggestions and open to debate :) Just wanted to be sure no offense taken :)

List of improvements:

- Add `.gitattributes` to force end of file to `LF` avoid conflict due to Windows :smiling_imp: 
- Use paket to mange all deps even `dotnet-fable` and `FSharp.NET.Sdk`
- I also run `.paket/paket update` and `yarn upgrade` so ATM we have the latest version of all deps
- Remove `Fable.Powerpack` because was not used and not useful for every libs
- Remove unused `open` declaration
- Simply the basic lib to only the simple `add` function
  - `[<Import("parseJson", "./custom.js")>] ` was invalid IMO because not `custom.js` presents and can't assume people want it. Better to keep the templates minimalist from my experience.
  - `let foo () = 3` same reason as latter
- Use `importSideEffects` to include the test file. According to your comment you want to use this import helper
- Make the current version of `MyLib.fsproj` equal to `0.0.0` (reason comes after)
- Change to the `build.fsx`
  - Make `fable` start on a "free" port. Useful, if you have several Fable project on your computer you can have them all started at the same time. (this choose a random free port)
  - Change `Publish` target to only publish if a new version is declared in the RELEASE_NOTES.md
    - If your version end with `next`, them no publish needed as it's in development
    - If your version is the same, no publish needed
    - If your version is different, then it's publish it and also change the version in `MyLib.fsproj` to the new version

Before merging this PR, we have some more actions needed and also decisions :)
- [x] Are we keeping them all ?
  - [x] If yes, we need to add instruction on how to use the template. Especially about the `Publish` target
- [x] I would also remove this lines [build.fsx#L81](https://github.com/MangelMaxime/Fable.Library.Template/blob/44d7ea66bdb93c4de5c8be0d76c8e143eef2b80a/Content/build.fsx#L81) and [build.fsx#L126-L130](https://github.com/MangelMaxime/Fable.Library.Template/blob/44d7ea66bdb93c4de5c8be0d76c8e143eef2b80a/Content/build.fsx#L126-L130)

I don't see the benefits of this lines and also "forcing" the version do nothing here. Quoting myself from gitter channel:

> But we are using ProjectReference so this do nothing no ?
> As a "proof" I have the version of the proj1 set to 0.0.0 in the fsproj and 0.1.0 is the version required by release.NugetVersion and the build + test are passing.
> Can we remove that ?

Sorry for this long changelog...

### CODE REVIEW

**Comment by TheAngryByrd** [comment]
First off thanks for this!  


> Add .gitattributes to force end of file to LF avoid conflict due to Windows 😈

👍 
> Use paket to mange all deps even dotnet-fable and FSharp.NET.Sdk

👍 but does paket handle `FSharp.NET.Sdk` correctly?  i.e. doesn't make it part of the nuspec when we run `dotnet pack` ?  I thought that was the point of `PrivateAssets="All"`.  

> I also run .paket/paket update and yarn upgrade so ATM we have the latest version of all deps

👍 

> Remove Fable.Powerpack because was not used and not useful for every libs

👍
 
> Remove unused open declaration

👍 

> Simply the basic lib to only the simple add function
[<Import("parseJson", "./custom.js")>] was invalid IMO because not custom.js presents and can't assume people want it. Better to keep the templates minimalist from my experience.
let foo () = 3 same reason as latter

👍 yeah might be better to include a link on javascript interop best practices then such as https://medium.com/@zaid.naom/f-interop-with-javascript-in-fable-the-complete-guide-ccc5b896a59f

> Use importSideEffects to include the test file. According to your comment you want to use this import helper

👍 A lot of this is cherry picked from what [I've seen in the wild](https://github.com/fable-compiler/fable-powerpack/blob/master/tests/Main.fs).  So improvements like this are great!


> Make fable start on a "free" port. Useful, if you have several Fable project on your computer you can have them all started at the same time. (this choose a random free port)

👍 Oh didn't realize it didn't do this by default.

I'm gonna address this one first:

> I would also remove this lines build.fsx#L81 and build.fsx#L126-L130
> I don't see the benefits of this lines and also "forcing" the version do nothing here. Quoting myself from gitter channel:

I wouldn't remove the release notes part unless there's an alternate way. 


> Make the current version of MyLib.fsproj equal to 0.0.0 (reason comes after)
> Change Publish target to only publish if a new version is declared in the RELEASE_NOTES.md
> If your version end with next, them no publish needed as it's in development
> If your version is the same, no publish needed
> If your version is different, then it's publish it and also change the version in MyLib.fsproj to the new version

The reason I publish the version through the cli is I don't like to mess around with people's project files if at all possible.  People [shuffle things around](https://github.com/fable-elmish/elmish/blob/master/build.fsx#L52), weird spacing or what have you can make this kind of stuff break, but I'm open to it if people are confident this is how it should be done.

However, the "forcing: part is a product of not putting a version in the Project file.  Say you have two projects Proj1 and Proj2.  Proj2 references Proj1. When you goto `dotnet restore` + `dotnet pack` nuspec chooses to reference Proj1 as 1.0.0 so when you goto download Proj2 you might not download the correct version.  This is definitely an issue for 0.x versions. So if we go with the method of replacing the version number in the project file the forcing part probably isn't needed.  

Also, I do really like being able to check not needing to publish if the version in release hasn't changed. 

I would want some other people's feedback on this particular part before I'd lean either way.

**Comment by MangelMaxime** [comment]
> but does paket handle FSharp.NET.Sdk correctly? i.e. doesn't make it part of the nuspec when we run dotnet pack ? I thought that was the point of PrivateAssets="All".

Ah yes I just checked one of [my lib](https://www.nuget.org/packages/Fable.Elmish.Bulma/0.1.0-alpha9) and indeed it have `FSharp.Net.Sdk` as a deps. I don't know if it's a bad or good thing. Perhaps @forki can help here ?

> I wouldn't remove the release notes part unless there's an alternate way.

Could you tell me whats the effect of the releases notes added here ? I will update the PR to remove the 
`p:PackageVersion` so.

I am not sure to understand your last comments block. The library template is only about providing a template for **1** IMO. If you have `Lib1` and `Lib2` then you got two different projects.
If `Lib2` depends on `Lib1`, then you publish your new version of `Lib1` to nuget. And after you publish your new version of `Lib2` with the updated dependencies.
For example: It's how Elmish works.

It's work the same as for application. Example for Ionide (which depends on a lot of project)
I recently made an update to `fsharp-gramar` so we push the change on this project. And after, we updated `ionide-vscode` deps to include them.

**Comment by MangelMaxime** [comment]
Ah yes I forget to say something :)
If people have the ability to customize their build system then they can easily understand the current one with the version checking and remove or adapt it to their need. After, I didn't test the behavior of pushing the same version twice. I will try it later and adapt the build.fsx accordingly

**Comment by MangelMaxime** [comment]
Ok so seems like `FSharp.NET.Sdk` should no be included as a deps.
I am trying to see if paket can handle this scenario or not. I don't like the idea of having the version of just one deps not fixed (bad experience because of that in the past) ^^.

Will see

**Comment by MangelMaxime** [comment]
@TheAngryByrd I updated the PR with the change we agreed on.

I tested to push twice the same version of a lib and we got an error from nuget.org not really nice output.
So we could remove all the boilerplate I added to "Publish" target. So it's up to you if we let it or no.

Personnally, I like my proposition because it's easy to publish a new version. Useful to have a simple way to push new version when you have a lot of libs. It's not fun to update manually several files :) (yes I am lazy^^)

**Comment by MangelMaxime** [comment]
Ah that's nice for the release note :) I need to add it to my libs.

-------

I think we can't solve all the problem. I consider this template to be of general purpose which is generally one repo git per lib. In the past, in Elmish we was having severals libs into the one repo and it's a mess to rollback if needed etc.

If the user, is skilled enough to write a lib into multiple part I consider him skilled enough to adapt his build system.

-------

For `dotnet push`, I don't know. I always used what I propose in the `build.fsx` and as it's working I am happy :)

**Comment by TheAngryByrd** [comment]
> I think we can't solve all the problem. I consider this template to be of general purpose which is generally one repo git per lib. In the past, in Elmish we was having severals libs into the one repo and it's a mess to rollback if needed etc.

> If the user, is skilled enough to write a lib into multiple part I consider him skilled enough to adapt his build system.

Fair enough. 👍 

> For dotnet push, I don't know. I always used what I propose in the build.fsx and as it's working I am happy :)

Ok, i just [asked in the paket gitter](https://gitter.im/fsprojects/Paket?at=599c5886ee5c9a4c5fea4a47) if one is preferred over the other.  After that this should be good to go.

---

I guess the last thing to do after that would be update the readme about the release semantics,  maybe similar to: https://github.com/TheAngryByrd/MiniScaffold#release

**Comment by MangelMaxime** [comment]
Sure, I will push the update this evening or tomorrow.

**Comment by MangelMaxime** [comment]
I updated the README, in fact it's mostly a copy/paste from your sample.

If you want to adjust it you can as I allowed you to edit my branch.

**Comment by alfonsogarciacaro** [comment]
First of all, thanks a lot @TheAngryByrd for this. We had to create a template for Fable libraries since a long time and I'm very happy that you started this so we can work on it and try to standardize best practices together. Thank you also @MangelMaxime for your suggestions, I'll try to make some comments on the points mentioned on top in case they are helpful:

- **FSharp.NET.Sdk**: In my experience, Paket can manage it without problems. In any case, we will soon upgrade Fable to netcore2 (a beta has already been published) and FSharp.NET.Sdk is not used with F# netcore2 projects anymore.
- **Fable.PowerPack**: One of the good things about Fable and JS bundlers is dependencies won't be included if they're not used, so just adding Fable.PowerPack is basically _free_, only the functions that are actually used (after tree shaking) will be included in the final JS bundle.
- **Importing JS code**: It'll be nice to have an example of how to interop with JS code and also mention @Zaid-Ajaj great guide, but yes, it'd be better to have an actual JS file for this (also see below about adding JS files to the Nuget package).
- **Project versioning**: I usually do like @MangelMaxime says. I like to put the version in the .fsproj because it's more or less similar to what's done in package.json files, but I understand @TheAngryByrd concerns about touching the .fsproj. Unfortunately there's no command in the dotnet SDK to bump version automatically as npm has, although regular expressions have worked well for me.

----------------------------

A few other general notes:

### Testing

The testing story also needs some improvement in Fable so it's very good that you added tests to the template. For now they should be fine as they're. About `importAll` vs `importSideEffects`, in this case both should be more or less equivalent, the latter was added just to make it more explicit that a file was being imported only for its side effects (like running some code, adding CSS rules, etc). We could also use fable-splitter instead of Webpack to avoid these manual imports, although we still need to add an option to fable-splitter to compile all files in the .fsproj.

Just a note about the assertions, you can use [Fable.Core.Testing.Assert.AreEqual](https://github.com/fable-compiler/Fable/blob/fbca7269418be7e8c3ebd94b36e35d410326b6e9/src/dotnet/Fable.Core/Fable.Core.fs#L140) which will use F# equality semantics and will throw an error with `actual` and `expected` fields so test runners like Mocha offer diffing in the results. This way, you don't need an assertion library either if you run the tests in the browser instead of node, for example.

### Distinction between bindings and Fable libraries

I know this is not always clear and can be confusing, so we may fix it later, but for now I'd like to keep the distinction between bindings and libraries for the reason [commented here](https://github.com/fable-compiler/fable-import/tree/7229f061e0ddeb172c785c11efce6c3f66b1313e#fable-import). Actually, there's no need to do anything about that in this repo but it's better to say this is not the template for a binding (for example in the README the name of the project sample is `CustomJsBinding`).

### Adding source files to Nuget package

As commented in the link above, Fable libraries [must include the source files](https://github.com/TheAngryByrd/Fable.Library.Template/blob/e33101a9c7fd5132951f627cd4d3fbe4ee8a6967/Content/src/Fable.MyLib.fsproj#L15) in the Nuget package. These are the conventions expected by Fable, and probably should be included in the README.

- There should be a folder named `fable` in the Nuget package.
- Immediately in this `fable` folder there should be a .fsproj file with the same name as the Nuget package.
- All source files referenced in the fsproj (and those JS files referenced with `import` expressions/attributes from F# code) must be included in the `fable` folder.

The last point is the trickiest one because it's difficult to cover most of the cases automatically, for example [the current item in the .fsproj](https://github.com/TheAngryByrd/Fable.Library.Template/blob/e33101a9c7fd5132951f627cd4d3fbe4ee8a6967/Content/src/Fable.MyLib.fsproj#L15) will only include .fsproj and .fs files in the root folder, if you have subfolders or other files (like .js) you must also specify them ([example](https://github.com/fable-compiler/fable-react-native/blob/6a7cc0e5074b985ef94e49a631cb8285eb9950c8/src/Fable.React.Native.fsproj#L32-L34)), so it'll be good to include some explanation in the README.

**Comment by MangelMaxime** [comment]
@alfonsogarciacaro About the latest point:

I am in fact using the next snippet for Fable.Elmish.Bulma and got no problem.
```
<ItemGroup>
    <Content Include="*.fsproj; **\*.fs" PackagePath="fable\" />
</ItemGroup>
```

**Comment by TheAngryByrd** [comment]
@alfonsogarciacaro Thanks for the input!

> Importing JS code ...

I agree having a simple example would be good.  I'll create a separate issue for it.

> Project versioning...

Ok cool, just wanted to have a second opinion. 👍 

>  Just a note about the assertions...

Awesome.  Will add that as an issue. 

> Distinction between bindings and Fable libraries

Oh wow I was not aware of this whatsoever.  I think this **needs to be clear**. Should we create a separate template for bindings? Maybe having separate template would make things clearer.

I was planning on releasing a binding for of OpenId Connect lib https://github.com/IdentityModel/oidc-client-js > https://github.com/TheAngryByrd/FableWithIdentityServer/blob/master/src/AppClient/Fable.Import.Oidc.fs .  So this is definitely good to know. 

I'll open another issue about making this explicit this is for `Fable Libraries ™ ` and not `Fable Bindings ™ `

**Comment by alfonsogarciacaro** [comment]
Yes, the reason to tell bindings and libraries apart is bindings don't contain any real code, so you don't need to include the sources in the package and Fable can reference the .dll directly. This makes parsing the project much faster specially for big bindings (please note I'm talking about bindings which don't contain any helper code).

Ideally, bindings should be made automatically by ts2fable (I'm currently updating it) so a specific template shouldn't be needed for them.

**Comment by MangelMaxime** [comment]
@TheAngryByrd Is there something missing in the current PR state ?

**Comment by TheAngryByrd** [comment]
Sorry just been a long week :)

**Comment by MangelMaxime** [comment]
No worries :)

**Pull request merged**
